[application]

[web.app]

# HTML title tag content
title = "0xNAME Sepolia ETH Faucet"
description = "0xname.foo is a public good platform for web3 users to seamlessly create free personal names associated with various web3 communities and projects"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
