[package]
name = "ui"
version.workspace = true
edition.workspace = true

[dependencies]
dioxus = { workspace = true }
server = { workspace = true }
shared-types.workspace = true
chrono.workspace = true 
