[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
server = { workspace = true, default-features = false }
shared-types.workspace = true
chrono.workspace = true 