[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
fjall.workspace = true
thiserror.workspace = true
rmp-serde.workspace = true
shared-types.workspace = true
format-bytes.workspace = true
[dev-dependencies]
tempfile = "3.3"